### ISSUE TITLE
Errors when running without arguments

### ISSUE THREAD

**Issue by falkTX** [jhernberg/udev-rtirq#1]
Just installed, and run it without arguments as regular user. Ubuntu 14.04.
This is the output:
```
$ udev-rtirq 
/usr/bin/udev-rtirq: line 52: continue: only meaningful in a `for', `while', or `until' loop
/usr/bin/udev-rtirq: line 54: [: =: unary operator expected
pid 50's current scheduling policy: SCHED_OTHER
pid 50's current scheduling priority: 0
```

**Comment by falkTX** [comment]
The `continue` at line 52 seems to be a typo. should be `exit` instead.

**Comment by jhernberg** [comment]
Heh. Fixed, was left over from the previous loop based implementation :)

But I see that I'd better change the logger lines too.  It's no longer a daemon.
