### ISSUE TITLE
Main script should be installed in /usr/sbin/

### ISSUE THREAD

**Issue by falkTX** [jhernberg/udev-rtirq#2]
it's calling chrt, so it needs root permissions.
Consider installing it in /usr/sbin/

**Comment by jhernberg** [comment]
I'll need to think about this.

**Comment by jhernberg** [comment]
I come to the conclusion that this is a good idea, like that it's not in the user's path as it's not meant to be run by the user (at least on systems that don't symlink everything to /usr/bin). Done!

**Comment by dvzrv** [comment]
Hmm, so why not making this settable through the [Makefile](https://github.com/jhernberg/udev-rtirq/blob/master/Makefile#L14) then?
At least for Arch (and probably others, that don't use the special /usr/sbin folder), this doesn't make sense, [as it collides with the Arch packaging standards](https://wiki.archlinux.org/index.php/Arch_packaging_standards#Directories).

**Comment by jhernberg** [comment]
Hmm, IMO Archlinux misses the point completely on this matter, and is actually itself not following long established standards..  That said I'm most likely moving it back to /usr/bin and adding some useful output similar to "rtirq status".  Also I just made the makefile to let people install it manually and to give packagers an idea of where things go, wouldn't change it just to support an Archlinux anomaly :)
